### ISSUE TITLE
CHAPTER 1 

### ISSUE THREAD

**Issue by amolchourasia27** [WebHostingServer/ProgressLogger-#1]
- [ ] exercise 1 
- [ ] exercise 2
- [ ] exercise 3

**Comment by amolchourasia27** [comment]
After completing inset images to show progress

**Comment by Ananychourasia** [comment]
> - [ ] exercise 1 
> - [ ] exercise 2
> - [ ] exercise 3
**DONE**

**Comment by WebHostingServer** [comment]
@Ananychourasia
