### ISSUE TITLE
Chapter 2 maths

### ISSUE THREAD

**Issue by WebHostingServer** [WebHostingServer/ProgressLogger-#2]
### chapter2

- [ ] ex1
- [ ] ex2
- [ ] #3
-to @Ananychourasia

**Comment by Ananychourasia** [comment]
> ### chapter2
> 
> - [ ] ex1
> - [ ] ex2
> - [ ] #3
> -to @Ananychourasia
> 

Completed ch2 
![IMG-20210827-WA0021.jpg](https://user-images.githubusercontent.com/85672926/131207113-adbd5ff0-7baf-45cd-ac5d-90904aaa65d7.jpg)
