### ISSUE TITLE
Study Task

### ISSUE THREAD

**Issue by WebHostingServer** [WebHostingServer/ProgressLogger-#5]
### Chapter 5
- [ ]  Exercise 5.2
- [ ]  Exercise 3.1 (Revision)
@AnanyChourasia

**Complete** Before     ---> Sunday 4:30 pm
_Rewards_  if Before  4:30     ---> gta/no app lock

**Comment by Ananychourasia** [comment]
Excercise 5.2 completed![IMG_20210829_145907.jpg](https://user-images.githubusercontent.com/85672926/131245665-964b99c5-d0fb-471d-89bd-fd484c1dd882.jpg)

**Comment by Ananychourasia** [comment]
Excercise 3.1 revision done ![IMG_20210829_160533.jpg](https://user-images.githubusercontent.com/85672926/131247400-9b4dde04-ad3a-423b-b6cd-9877c8b24eba.jpg)

**Comment by WebHostingServer** [comment]
**Good first Job **
